### ISSUE TITLE
Error since wp-graphql v0.4.0

### ISSUE THREAD

**Issue by ramykl** [DalkMania/wp-graphql-mb#4]
Looks like this is broken again since wp-graphql v0.4.0 see breaking changes (https://github.com/wp-graphql/wp-graphql/releases/tag/v0.4.0) gives the following error:
```
Fatal error: Uncaught Error: Call to undefined method WPGraphQL\Types::list_of() in /srv/wp-content/plugins/wp-graphql-mb/wp-graphql-mb.php:92 
Stack trace: 
#0 /srv/wp-content/plugins/wp-graphql-mb/wp-graphql-mb.php(54): WPGraphQL\Extensions\MB->add_meta_fields(Object(WPGraphQL\Registry\TypeRegistry), 'page') 
#1 /srv/wp/wp-includes/class-wp-hook.php(286): WPGraphQL\Extensions\MB->WPGraphQL\Extensions\{closure}(Object(WPGraphQL\Registry\TypeRegistry)) 
#2 /srv/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(Object(WPGraphQL\Registry\TypeRegistry), Array) 
#3 /srv/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#4 /srv/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(219): do_action('graphql_registe...', Object(WPGraphQL\Registry\TypeRegistry)) 
#5 /srv/wp/wp-includes/class-wp-hook.php(286): WPGraphQL\Registry\TypeRegistry->init_type_registry(Object(WPGraphQL\Registry\TypeRegistry)) 
#6 /srv/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
#7 /srv/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#8 /srv/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(194): do_action('init_graphql_ty...', Object(WPGraphQL\Registry\TypeRegistry)) 
#9 /srv/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php(36): WPGraphQL\Registry\TypeRegistry->init() 
#10 /srv/wp-content/plugins/wp-graphql/wp-graphql.php(556): WPGraphQL\Registry\SchemaRegistry->get_schema() 
#11 /srv/wp-content/plugins/wp-graphql/src/Request.php(88): WPGraphQL::get_schema() 
#12 /srv/wp-content/plugins/wp-graphql/src/Router.php(394): WPGraphQL\Request->__construct() 
#13 /srv/wp-content/plugins/wp-graphql/src/Router.php(221): WPGraphQL\Router::process_http_request() 
#14 /srv/wp/wp-includes/class-wp-hook.php(286): WPGraphQL\Router->resolve_http_request(Object(WP)) 
#15 /srv/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) 
#16 /srv/wp/wp-includes/plugin.php(515): WP_Hook->do_action(Array) 
#17 /srv/wp/wp-includes/class-wp.php(375): do_action_ref_array('parse_request', Array) 
#18 /srv/wp/wp-includes/class-wp.php(715): WP->parse_request('') 
#19 /srv/wp/wp-includes/functions.php(960): WP->main('') 
#20 /srv/wp/wp-blog-header.php(16): wp() 
#21 /srv/wp/index.php(17): require('/srv/wp/wp-blog...') 
#22 /srv/gae-app.php(84): require('/srv/wp/index.p...')
 #23 {main} thrown in /srv/wp-content/plugins/wp-graphql-mb/wp-graphql-mb.php on line 92
```
Unfortunately, I don't know enough PHP to fix this based on what they say in the v0.4.0 release notes

**Comment by DalkMania** [comment]
Thanks @ramykl 

I'll see to it to get this updated. It has been stale for some time.
